load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Lib_Swift",
    srcs = glob(["src/**"]),
    visibility = ["//visibility:public"],
    module_name = "AppLib",
)
