load("//TextureApp.xcodeproj/XCHammerAssets:Hammer.bzl", "export_entitlements")
export_entitlements(
  name = "ios-app-share-extension_entitlements",
  entitlements = None,
  provisioning_profile = None,
  bundle_id = "Google.TextureApp.ShareExtension",
  platform_type = "ios"
)
export_entitlements(
  name = "ios-app-ios-app_entitlements",
  entitlements = None,
  provisioning_profile = None,
  bundle_id = "Google.TextureApp",
  platform_type = "ios"
)
export_entitlements(
  name = "ios-app-strings-extension_entitlements",
  entitlements = None,
  provisioning_profile = None,
  bundle_id = "Google.TextureApp.StringsExtension",
  platform_type = "ios"
)